language: ruby
rvm:
  - 2.4
cache: bundler

sudo: false

script:
  - set -e
  - bundle exec jekyll build -d _site
  - git config --global user.name "Travis"
  - git config --global user.email "fantasticfears@gmail.com"
  - git checkout -b deploy
  - git add -f _site/
  - git commit -a -m "Deploy"
  - git checkout gh-pages
  - git checkout deploy _site/**
  - rsync -av _site/ .
  - rm -rf _site
  - git add . && git commit -a -m "Deploy ${CIRCLE_BUILD_NUM}" && git push origin gh-pages --force --quiet "https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@${GIT_TARGET}" master:master > /dev/null 2>&1
