version: 2.1

workflows:
  tests:
    jobs:
      - build:
        filters:
          branches:
            only: post

orbs:
  ruby: circleci/ruby@1.8.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
        auth:
          username: fantasticfears
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - ruby/install-deps # use the ruby orb to install dependencies
      - run: bundle exec jekyll build
      - run: bundle exec htmlproofer ./_site --check-html --disable-external