version: 2
jobs:
  build:
    docker:
       - image: jekyll/builder
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "Gemfile.lock" }}
          - v6-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - ~/.gem/gems 
            - ~/.rvm/gems
          key: v6-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run: bundle exec jekyll build -d _site

      - deploy:
          name: Bump sites
          command: |
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git config --global user.email "${CIRCLE_PROJECT_USERNAME}@${CIRCLE_PROJECT_USERNAME}"
            git checkout -b deploy
            git add -f _site/
            git commit -a -m "Deploy"
            git checkout gh-pages
            git checkout deploy _site/**
            mkdir /tmp/artifacts
            rsync -av _site/ . > /tmp/artifacts/${CIRCLE_BUILD_NUM}.txt
            rm -rf _site
            git add . && git commit -a -m "Deploy ${CIRCLE_BUILD_NUM}" && git push origin gh-pages
      
      - store_site_directory:
        name: Store site directory
        type: store_test_results
        path: /tmp/artifacts
