version: 2
jobs:
  build:
    docker:
       - image: jekyll/builder
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - vendor/bundle 
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run: bundle exec jekyll build -d _site

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec htmlproofer ./_site \
                            --check-html \
                            --disable-external \
                            --assume-extension \
                            > /tmp/test-results/htmlproofer.txt

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      - deploy:
          name: Bump sites
          command: |
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git config --global user.email "${CIRCLE_PROJECT_USERNAME}@${CIRCLE_PROJECT_USERNAME}"
            git checkout -b deploy
            git add -f _site/
            git commit -a -m "Deploy"
            git checkout gh-pages
            git checkout deploy _site/**
            cp -r _site/ .
            rm -rf _site
            git add . && git commit -a -m "Deploy ${CIRCLE_BUILD_NUM}" && git push origin gh-pages
