version: 2
jobs:
  build:
    docker:
       - image: jekyll/builder
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "Gemfile.lock" }}
          - v4-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle 
          key: v4-dependencies-{{ checksum "Gemfile.lock" }}
      
      - run: bundle exec jekyll build -d _site

      - deploy:
          name: Bump sites
          command: |
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git config --global user.email "${CIRCLE_PROJECT_USERNAME}@${CIRCLE_PROJECT_USERNAME}"
            git checkout -b deploy
            git add -f _site/
            git commit -a -m "Deploy"
            git checkout gh-pages
            git checkout deploy _site/**
            cp -r _site/ .
            rm -rf _site
            git add . && git commit -a -m "Deploy ${CIRCLE_BUILD_NUM}" && git push origin gh-pages
